### ISSUE TITLE
Error: Cannot find module './certificate'

### ISSUE THREAD

**Issue by loretoparisi** [joyent/node-sshpk#14]
I get this error since latest version, when installing on Azure Web Sites. Before it was working.

```shell
Application has thrown an uncaught exception and is terminated:
Error: Cannot find module './certificate'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\home\site\wwwroot\bot\node_modules\sshpk\lib\fingerprint.js:10:19)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
```

**Comment by loretoparisi** [comment]
@arekinath Thank you, I have found that it was like a continuos  deploy issue on the Azure Web Site machine, checking the console after several attempts, I get all files there

![schermata 2016-08-26 alle 11 10 34](https://cloud.githubusercontent.com/assets/163333/18000336/c2d44250-6b7d-11e6-9468-186eb9aa1a01.jpg)

Now it works ok!
