### ISSUE TITLE
Add support for sk-ecdsa-sha2-nistp256@openssh.com and sk-ssh-ed25519@openssh.com

### ISSUE THREAD

**Issue by fbettag** [joyent/node-sshpk#72]
Can we add support for sk-ssh-ed25519@openssh.com and sk-ecdsa-sha2-nistp256@openssh.com keys. Maybe even check https://man.openbsd.org/sshd#AUTHORIZED_KEYS_FILE_FORMAT for other formats this is missing :)

**Comment by ThibaudLopez** [comment]
We confirm the bug:

Here are two examples of valid SSH public key fingerprints, they are from physical security keys, where prefix `sk` is for SSH Security Keys, see https://www.yubico.com/blog/github-now-supports-ssh-security-keys/ :

```bash
> cat .ssh/id_ecdsa_sk.pub
sk-ecdsa-sha2-nistp256@openssh.com AAAAInNrLWVjZHNhLXNoYTItbmlzdHAyNTZAb3BlbnNzaC5jb20AAAAIbmlzdHAyNTYAAABBBAlulpLk2cp9XsbCWxwpxgKIBpxUlSki4Y3k+0huraRzVtYy4FaKyXGZ4kyCpkdhsSrkSD8ptbeks9lzV1tGe2wAAAAEc3NoOg== [REDACTED]@[REDACTED].com

> cat [REDACTED]
sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAIKdtLKvpwRRMdmoo1Exj8/MxSVOb5zN47eJmVg9ttVP2AAAABHNzaDo= [REDACTED]
```

But `sshpk` fails to parse them:

```js
let sshpk = require('sshpk');
sshpk.parseKey('sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAIKdtLKvpwRRMdmoo1Exj8/MxSVOb5zN47eJmVg9ttVP2AAAABHNzaDo=', 'ssh');
sshpk.parseKey('sk-ecdsa-sha2-nistp256@openssh.com AAAAInNrLWVjZHNhLXNoYTItbmlzdHAyNTZAb3BlbnNzaC5jb20AAAAIbmlzdHAyNTYAAABBBAlulpLk2cp9XsbCWxwpxgKIBpxUlSki4Y3k+0huraRzVtYy4FaKyXGZ4kyCpkdhsSrkSD8ptbeks9lzV1tGe2wAAAAEc3NoOg==', 'ssh');
```

```
Uncaught:
KeyParseError: Failed to parse (unnamed) as a valid ssh format key: key must match regex
    at Object.Key.parse [as parseKey] (node_modules/sshpk/lib/key.js:261:10) {
  format: 'ssh',
  keyName: '(unnamed)',
  innerErr: AssertionError [ERR_ASSERTION]: key must match regex
      at Object.read (node_modules/sshpk/lib/formats/ssh.js:32:9)
      at Object.Key.parse [as parseKey] (node_modules/sshpk/lib/key.js:252:27)
      at Script.runInThisContext (node:vm:129:12)
      at REPLServer.defaultEval (node:repl:566:29)
      at bound (node:domain:421:15)
      at REPLServer.runBound [as eval] (node:domain:432:12)
      at REPLServer.onLine (node:repl:893:10)
      at REPLServer.emit (node:events:539:35)
      at REPLServer.emit (node:domain:475:12) {
    generatedMessage: false,
    code: 'ERR_ASSERTION',
    actual: null,
    expected: true,
    operator: '=='
  }
}
```
